name: Create Pull Request
on:
  workflow_dispatch:

jobs:
  create-pr:
    uses: aparnajyothi-y/versions-package-tools/.github/workflows/create-pr-to-update-manifest.yml@ubuntu-24-fixes
    with:
      tool-name: "go"
    secrets: inherit
